[project]
name = "acme-lib-b"
version = "0.0.0"
description = ""
requires-python = ">=3.8"
dependencies = [
    "acme-lib-c",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
